version: "3"

services:
  web:
    image: python:3.10
    build:
      context: ./fashion_shopping_backend
    working_dir: /app/web
    restart: always
    volumes:
      - ./fashion_shopping_backend/:/app/web/
      - ./fashion_shopping_backend/media/:/app/web/media/
      - static:/app/web/static/
      - media:/app/web/media/
    entrypoint: sh entrypoint.sh
    command: python3 manage.py deploy
    depends_on:
      - db
      - redis

  celery_worker:
    build:
      context: ./fashion_shopping_backend
    volumes:
      - ./fashion_shopping_backend/:/app/web/
      - static:/app/web/static/
      - media:/app/web/media/
    command: celery -A fashion_shopping_backend.celery worker -l info
    depends_on:
      - redis

  celery_beat:
    build:
      context: ./fashion_shopping_backend
    volumes:
      - ./fashion_shopping_backend/:/app/web/
      - static:/app/web/static/
      - media:/app/web/media/
    command: celery -A fashion_shopping_backend.celery beat -l info
    depends_on:
      - redis

  image_search:
    image: python:3.10
    build:
      context: ./fashion_shopping_image_search
    working_dir: /app/image_search
    volumes:
      - ./fashion_shopping_image_search/:/app/image_search/
      - media:/media/
    # restart: always
    environment:
      - PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
    command: python3 api.py
    depends_on:
      - db

  chatbot:
    image: rasa/rasa:3.4.2-full
    build:
      context: ./fashion_shopping_chatbot
    volumes:
      - ./fashion_shopping_chatbot/:/app/chatbot/
    # restart: always
    env_file:
      - ./fashion_shopping_chatbot/.env
    command: run

  rasa_actions:
    build:
      context: ./fashion_shopping_chatbot
    volumes:
      - ./fashion_shopping_chatbot/:/app/chatbot/
    env_file:
      - ./fashion_shopping_chatbot/.env
    restart: always
    command: run actions

  # fe_admin:
  #   image: node:16
  #   build:
  #     context: ./fashion_shopping_admin
  #   env_file:
  #     - ./fashion_shopping_admin/.env
  #   command: yarn start

  db:
    image: postgres:15.1
    restart: always
    volumes:
      - ./database/data/:/var/lib/postgresql/data/
    env_file:
      - ./database/.env
    ports:
      - 5432:5432

  proxy:
    image: nginx:1.23
    build:
      context: ./nginx
    volumes:
      - static:/static/
      - media:/media/
    ports:
      - 8000:8000
      - 5005:5005
      # - 3000:3000
    depends_on:
      - web

  redis:
    image: redis:7.0

volumes:
  static:
  media:
